name: Web3Jobs Workflow

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install Python dependencies using uv
        run: |
          uv venv
          uv pip install -r ${{ github.workspace }}/requirements.txt
          echo "Dependency installation step finished."

      - name: Run scripts
        run: |
          python run_all_tasks.py
