name: Scheduled Data Collection

on:
  schedule:
    - cron: '0 */6 * * *'  # Runs at 00:00, 06:00, 12:00, 18:00 UTC
  workflow_dispatch:  # Allows manual triggering from GitHub Actions tab

jobs:
  collect_and_process:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Install uv (modern pip alternative)
      run: |
        echo "Installing uv..."
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "::add-path::${HOME}/.local/bin"  # Add to PATH
        uv --version
        which uv  # Verify uv is found in the PATH

    - name: Create and activate virtual environment
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install -r ${{ github.workspace }}/requirements.txt
        echo "Dependency installation step finished."

    - name: Run the master task script
      env:
        POSTGRES_URI: ${{ secrets.POSTGRES_URI }}
        MONGO_URI: ${{ secrets.MONGO_URI }}
        REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
        REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
        REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
        TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
        WEB3_CAREER_API_KEY: ${{ secrets.WEB3_CAREER_API_KEY }}
      run: |
        echo "Executing master Python script..."
        source venv/bin/activate
        python3 /home/runner/work/web3Jobs/web3Jobs/run_all_tasks.py

    - name: Debug Environment Variables
      run: |
        echo "POSTGRES_URI: $POSTGRES_URI"
        echo "MONGO_URI: $MONGO_URI"
        echo "REDDIT_CLIENT_ID: $REDDIT_CLIENT_ID"
        echo "REDDIT_USER_AGENT: $REDDIT_USER_AGENT"

    - name: Post Set up Python
      if: always()  # Ensure this step always runs
      run: |
        echo "Post setup tasks here..."
