- name: Debug environment
  run: |
    echo "GitHub Workspace: ${{ github.workspace }}"
    echo "Current directory: $(pwd)"
    echo "Repository contents:"
    find ${{ github.workspace }} -type f -name "*.py" | sort
    find ${{ github.workspace }} -type f -name "requirements.txt" | sort
