name: Scheduled Data Collection

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC

jobs:
  collect_and_process:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install uv
        run: |
          pip install uv

      - name: Install Python dependencies using uv
        run: |
          uv venv
          if [ -d ".venv" ]; then
            echo ".venv directory created successfully."
          else
            echo "Failed to create .venv directory."
            exit 1
          fi
          uv pip install -r ${{ github.workspace }}/requirements.txt
          echo "Dependency installation step finished."

      - name: Run data collection script
        run: |
          uv run python scripts/collect_data.py
