name: Scheduled Data Collection

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  collect_and_process:
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: List repository files and check for required files
        run: |
          echo "Listing files in ${{ github.workspace }}:"
          ls -la ${{ github.workspace }}
          echo "Checking for requirements.txt:"
          if [ -f "${{ github.workspace }}/requirements.txt" ]; then
            echo "✓ requirements.txt found."
          else
            echo "✗ requirements.txt NOT found."
          fi
          echo "Checking for test_imports.py:"
          if [ -f "${{ github.workspace }}/test_imports.py" ]; then
            echo "✓ test_imports.py found."
          else
            echo "✗ test_imports.py NOT found."
          fi
          echo "Checking for run_all_tasks.py:"
          if [ -f "${{ github.workspace }}/run_all_tasks.py" ]; then
            echo "✓ run_all_tasks.py found."
          else
            echo "✗ run_all_tasks.py NOT found."
          fi

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          if [ -f "${{ github.workspace }}/requirements.txt" ]; then
            python -m pip install --upgrade pip
            pip install -r ${{ github.workspace }}/requirements.txt
          else
            echo "✗ ERROR: requirements.txt not found. Cannot install dependencies."
            exit 1
          fi

      - name: Run import test script
        run: |
          if [ -f "${{ github.workspace }}/test_imports.py" ]; then
            echo "Running test_imports.py..."
            python3 ${{ github.workspace }}/test_imports.py
          else
            echo "Error: test_imports.py not found."
            exit 1
          fi

      - name: Verify Secrets are Available
        run: |
          echo "--- Verifying Secrets ---"
          all_secrets_set=true
          if [[ -z "${{ secrets.POSTGRES_URI }}" ]]; then echo "✗ ERROR: POSTGRES_URI is NOT SET"; all_secrets_set=false; else echo "✓ POSTGRES_URI: Set"; fi
          if [[ -z "${{ secrets.MONGO_URI }}" ]]; then echo "✗ ERROR: MONGO_URI is NOT SET"; all_secrets_set=false; else echo "✓ MONGO_URI: Set"; fi
          if [[ -z "${{ secrets.REDDIT_CLIENT_ID }}" ]]; then echo "✗ ERROR: REDDIT_CLIENT_ID is NOT SET"; all_secrets_set=false; else echo "✓ REDDIT_CLIENT_ID: Set"; fi
          if [[ -z "${{ secrets.REDDIT_CLIENT_SECRET }}" ]]; then echo "✗ ERROR: REDDIT_CLIENT_SECRET is NOT SET"; all_secrets_set=false; else echo "✓ REDDIT_CLIENT_SECRET: Set"; fi
          if [[ -z "${{ secrets.REDDIT_USER_AGENT }}" ]]; then echo "✗ ERROR: REDDIT_USER_AGENT is NOT SET"; all_secrets_set=false; else echo "✓ REDDIT_USER_AGENT: Set"; fi
          if [[ -z "${{ secrets.TWITTER_BEARER_TOKEN }}" ]]; then echo "✗ ERROR: TWITTER_BEARER_TOKEN is NOT SET"; all_secrets_set=false; else echo "✓ TWITTER_BEARER_TOKEN: Set"; fi
          if [[ -z "${{ secrets.WEB3_CAREER_API_KEY }}" ]]; then echo "✗ ERROR: WEB3_CAREER_API_KEY is NOT SET"; all_secrets_set=false; else echo "✓ WEB3_CAREER_API_KEY: Set"; fi
          echo "--- Secrets Verification Done ---"
          if [ "$all_secrets_set" = false ]; then echo ">>> CRITICAL: One or more required secrets are missing!"; exit 1; fi

      - name: Run Data Collection Tasks (Master Script)
        env:
          POSTGRES_URI: ${{ secrets.POSTGRES_URI }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
          WEB3_CAREER_API_KEY: ${{ secrets.WEB3_CAREER_API_KEY }}
        run: |
          if [ -f "${{ github.workspace }}/run_all_tasks.py" ]; then
            echo "Executing master script: python3 ${{ github.workspace }}/run_all_tasks.py"
            python3 ${{ github.workspace }}/run_all_tasks.py
            echo "Master script execution finished."
          else
            echo "Error: run_all_tasks.py not found."
            exit 1
          fi
