- name: Run the master task script
  env:
    POSTGRES_URI: ${{ secrets.POSTGRES_URI }}
    MONGO_URI: ${{ secrets.MONGO_URI }}
    REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
    REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
    REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
    TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
    WEB3_CAREER_API_KEY: ${{ secrets.WEB3_CAREER_API_KEY }}
  run: |
    echo "Executing master Python script with absolute path..."
    source venv/bin/activate  # Ensure the environment is activated
    python3 /home/runner/work/web3Jobs/web3Jobs/run_all_tasks.py
    echo "Master script execution finished."
  continue-on-error: true
