# CLEANED VERSION - Use only after confirming the debug version runs successfully

name: Scheduled Data Collection

on:
  schedule:
    # Runs every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch: # Allows manual runs

jobs:
  collect_and_process:
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
    # Step 1: Checkout code
    - name: Check out repository code
      uses: actions/checkout@v4

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # Step 3: Install dependencies
    - name: Install Python dependencies using pip
      run: |
        python -m pip install --upgrade pip
        # Assumes requirements.txt exists at root after checkout
        pip install -r ${{ github.workspace }}/requirements.txt
        echo "Dependencies installed."

    # Step 4: Verify secrets availability (Quick check still useful)
    - name: Verify Secrets are Available
      run: |
        echo "--- Verifying Secrets ---"
        all_secrets_set=true
        # Simple check if variable length is non-zero
        [[ -z "${{ secrets.POSTGRES_URI }}" ]] && { echo "✗ ERROR: POSTGRES_URI is NOT SET"; all_secrets_set=false; } || echo "✓ POSTGRES_URI: Set"
        [[ -z "${{ secrets.MONGO_URI }}" ]] && { echo "✗ ERROR: MONGO_URI is NOT SET"; all_secrets_set=false; } || echo "✓ MONGO_URI: Set"
        [[ -z "${{ secrets.REDDIT_CLIENT_ID }}" ]] && { echo "✗ ERROR: REDDIT_CLIENT_ID is NOT SET"; all_secrets_set=false; } || echo "✓ REDDIT_CLIENT_ID: Set"
        [[ -z "${{ secrets.REDDIT_CLIENT_SECRET }}" ]] && { echo "✗ ERROR: REDDIT_CLIENT_SECRET is NOT SET"; all_secrets_set=false; } || echo "✓ REDDIT_CLIENT_SECRET: Set"
        [[ -z "${{ secrets.REDDIT_USER_AGENT }}" ]] && { echo "✗ ERROR: REDDIT_USER_AGENT is NOT SET"; all_secrets_set=false; } || echo "✓ REDDIT_USER_AGENT: Set"
        [[ -z "${{ secrets.TWITTER_BEARER_TOKEN }}" ]] && { echo "✗ ERROR: TWITTER_BEARER_TOKEN is NOT SET"; all_secrets_set=false; } || echo "✓ TWITTER_BEARER_TOKEN: Set"
        [[ -z "${{ secrets.WEB3_CAREER_API_KEY }}" ]] && { echo "✗ ERROR: WEB3_CAREER_API_KEY is NOT SET"; all_secrets_set=false; } || echo "✓ WEB3_CAREER_API_KEY: Set"
        if [ "$all_secrets_set" = false ]; then exit 1; fi # Fail step if secrets missing

    # Step 5: Run the master task script
    - name: Run Data Collection Tasks (Master Script)
      env:
        POSTGRES_URI: ${{ secrets.POSTGRES_URI }}
        MONGO_URI: ${{ secrets.MONGO_URI }}
        REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
        REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
        REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
        TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
        WEB3_CAREER_API_KEY: ${{ secrets.WEB3_CAREER_API_KEY }}
      run: |
        echo "Executing master script: python3 ${{ github.workspace }}/run_all_tasks.py"
        python3 ${{ github.workspace }}/run_all_tasks.py
        echo "Master script execution finished."
